# Generated by Django 4.1.2 on 2022-11-10 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footage'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news')),
                ('title', models.CharField(max_length=150)),
                ('written_on', models.DateTimeField(default=datetime.datetime.now)),
                ('description_brief', models.CharField(max_length=150)),
            ],
        ),
    ]
