# Generated by Django 4.1.2 on 2022-11-13 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_news_access_count_alter_news_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comm', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news')),
            ],
        ),
    ]
