# Generated by Django 4.1.2 on 2022-11-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ipclients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPClients',
        ),
    ]
