# Generated by Django 4.1.2 on 2022-11-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_ipclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
