# Generated by Django 4.1.2 on 2022-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pending_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
