# Generated by Django 4.1.2 on 2022-11-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comments_pending_req_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.FileField(default='text_articles/dummy.txt', upload_to=''),
        ),
    ]
