# Generated by Django 4.1.2 on 2022-11-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_comments_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reason',
        ),
    ]
