# Generated by Django 4.1.2 on 2022-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_comments_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reason',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
