# Generated by Django 4.1.2 on 2022-11-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_comments_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reason',
            new_name='reason_report',
        ),
    ]
