# Generated by Django 4.1.2 on 2022-11-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_reason_comments_reason_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='pending_req',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='reason_report',
        ),
    ]
