# Generated by Django 4.1.2 on 2022-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_comments_pending_req_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pending_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='reason_report',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
