# Generated by Django 4.1.2 on 2022-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_comments_id_comments_id_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id_comm',
        ),
        migrations.AddField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
