# Generated by Django 4.1.2 on 2022-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_comments_id_comm_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
