# Generated by Django 4.1.2 on 2022-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reason_report',
            field=models.TextField(default='.', max_length=100),
        ),
    ]
