# Generated by Django 4.1.2 on 2022-11-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_comments_reason_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='footage',
            name='pending_req',
            field=models.BooleanField(default=False),
        ),
    ]
