# Generated by Django 4.1.2 on 2022-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_footage_pending_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='pending_req',
            field=models.BooleanField(default=True),
        ),
    ]
